repos:
#-   repo: https://github.com/pycqa/flake8
#    rev: 3.9.2
#    hooks:
#    - id: flake8
#      args:
#        - --config=.code_quality/.flake8
#-   repo: https://github.com/pycqa/pylint
#    rev: v2.8.2
#    hooks:
#    - id: pylint
#      args:
#      - --rcfile=.code_quality/.pylintrc
#-   repo: https://github.com/ambv/black
#    rev: 21.5b1
#    hooks:
#    - id: black
#      language_version: python3
#      args:
#          - --config
#          - .code_quality/pyproject_black.toml
#-   repo: https://github.com/PyCQA/bandit
#    rev: 1.7.0
#    hooks:
#    -   id: bandit
#        args:
#          - -c
#          - .code_quality/bandit.yaml
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.812'
#    hooks:
#    -   id: mypy
#        args:
#          - --config-file=.code_quality/mypy.ini
  - repo: https://github.com/melisource/fury_websec-git-hooks
    rev: v1.1.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [commit]
  - repo: https://github.com/mercadolibre/fury_datasec-git-hooks
    rev: 1.0.1

    hooks:
      - id: pre_commit_hook
        stages: [commit]
        verbose: true
